package neo.reducecognitivecomplexity.core.refactoringcache;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Stack;

import org.eclipse.jdt.core.dom.ASTNode;
import org.eclipse.jdt.core.dom.CompilationUnit;
import org.eclipse.jdt.core.dom.EmptyStatement;

import neo.reducecognitivecomplexity.app.Constants;
import neo.reducecognitivecomplexity.core.Sequence;
import neo.reducecognitivecomplexity.core.jdt.CodeExtractionMetrics;
import neo.reducecognitivecomplexity.core.refactoringcache.ConsecutiveSequenceIterator.SentenceSequenceInfo;
import neo.reducecognitivecomplexity.core.solvers.exhaustivesearch.ExhaustiveEnumerationAlgorithm.Approach;

/**
 * Iterator that adapts the generic {@link ConsecutiveSequenceIterator} to work
 * with specific {@link Sequence} objects (lists of ASTNodes).
 * <p>
 * This class bridges the gap between raw integer indices generated by the
 * underlying iterator and the actual AST nodes representing code statements. It
 * checks validity using {@link RefactoringCache} to ensure extraction
 * feasibility.
 * </p>
 */
public class SentenceSequenceIterator implements Iterable<List<Sequence>> {

	// TODO: Improve efficiency (caching or optimizing AST lookups)

	private final CompilationUnit compilationUnit;
	private final Sequence sentences;
	private final ConsecutiveSequenceIterator csi;

	// Cached iterable to avoid recreating it multiple times
	private Iterable<List<Sequence>> iterable = null;

	/**
	 * Constructs a new iterator for sequence generation.
	 *
	 * @param sentences        The base sequence of sibling nodes to iterate over.
	 * @param refactoringCache The cache used to check feasibility of extractions.
	 * @param approach         The enumeration approach (e.g., Longest First).
	 */
	public SentenceSequenceIterator(Sequence sentences, RefactoringCache refactoringCache, Approach approach) {
		this.compilationUnit = refactoringCache.getCompilationUnit();
		this.sentences = sentences;

		// Initialize the underlying integer-based iterator with specific logic for
		// ASTNodes
		this.csi = new ConsecutiveSequenceIterator(new SentenceSequenceInfo() {

			@Override
			public int numberOfSentences() {
				return sentences.getSiblingNodes().size();
			}

			@Override
			public int cognitiveComplexityOfSentence(int sentence) {
				// Sentences are 1-based in the iterator, but 0-based in the list
				ASTNode node = sentences.getSiblingNodes().get(sentence - 1);

				Integer acc = (Integer) node.getProperty(Constants.ACCUMULATED_CONTRIBUTION_TO_COGNITIVE_COMPLEXITY);
				return (acc != null) ? acc : 0;
			}

			@Override
			public boolean validSequence(int from, int to) {
				// Empty statements (semicolons) are not valid extraction targets
				if (isEmptyStatement(from) || isEmptyStatement(to)) {
					return false;
				}

				// Check refactoring feasibility using the cache
				// Indices are converted to 0-based for subList (inclusive start, exclusive end)
				List<ASTNode> subList = sentences.getSiblingNodes().subList(from - 1, to);
				Sequence seqToCheck = new Sequence(refactoringCache.getCompilationUnit(), subList);

				CodeExtractionMetrics cem = refactoringCache.getMetrics(seqToCheck);
				return cem.isFeasible();
			}

			private boolean isEmptyStatement(int sentence) {
				ASTNode node = sentences.getSiblingNodes().get(sentence - 1);
				return (node instanceof EmptyStatement);
			}
		}, approach);
	}

	/**
	 * Returns the iterable capable of generating lists of Sequences.
	 * <p>
	 * Uses a lazy initialization pattern.
	 * </p>
	 * 
	 * @return An iterable of List<Sequence>.
	 */
	public Iterable<List<Sequence>> getIterable() {
		if (iterable == null) {
			// Adapts the integer stack from csi into a List<Sequence> using the adapt
			// method
			iterable = Utils.adapt(csi.getIterable(), this::adapt);
		}
		return iterable;
	}

	/**
	 * Adapts a stack of indices (start, end, start, end...) into a list of Sequence
	 * objects.
	 *
	 * @param stack Stack containing pairs of indices [start1, end1, start2, end2,
	 *              ...]
	 * @return A list of Sequence objects corresponding to those ranges.
	 */
	private List<Sequence> adapt(Stack<Integer> stack) {
		List<Sequence> result = new ArrayList<>();

		// Iterate by pairs (start, end)
		for (int i = 0; i < stack.size(); i += 2) {
			int start = stack.get(i);
			int end = stack.get(i + 1);

			// Extract the sublist of nodes for this range
			ArrayList<ASTNode> nodes = new ArrayList<>(sentences.getSiblingNodes().subList(start - 1, end));

			result.add(new Sequence(this.compilationUnit, nodes));
		}
		return result;
	}

	@Override
	public Iterator<List<Sequence>> iterator() {
		return getIterable().iterator();
	}
}