# ==========================================
# Cognitive Complexity Tool Configuration
# ==========================================
# update the paths for your local machine.

# The folder where the output CSVs files will be saved.
# Use forward slashes (/) or escaped backslashes (\\)
output.folder=./output/

# The cognitive complexity threshold to consider a 
# cognitive complexity issue on a method
complexity.threshold=15

# Maximum working memory (in megabytes) for solver 
working.memory=2048

# Maximum time limit (in seconds) for solver 
time.limit=300

# ==========================================
# CPLEX Configuration
# ==========================================
# IMPORTANT: The native library path must ALSO be passed as a VM argument 
# in your Eclipse Run Configuration. 
# Example VM Argument: -Djava.library.path="/path/to/cplex/bin/your_os_arch"
cplex.native.library.path=/Users/your_user_folder/your_cplex_folder/bin/arm64_osx